"use client";

import React, { useState } from "react";
import Image from "next/image";
import {
  Users,
  Brain,
  Lightbulb,
  Globe,
  MessageSquare,
  Cpu,
  Compass,
  Flag,
  Activity,
  ArrowLeft,
  ChevronRight,
} from "lucide-react";
import Artifact from "@/components/Artifact";
import Navbar from "@/components/Navbar";

const ARTIFACTS_DATA: Record<
  string,
  Array<{ title: string; img: string; description: string; date: string }>
> = {
  citizenship: [
    {
      title: "Philosophy Research",
      img: "/artifacts/21st/C-CCUS/philo.png",
      description:
        "Researching regarding what would be a detrimental Filipino culture in Philosophy",
      date: "October 2024",
    },
    {
      title: "UCSP Research - Part 1",
      img: "/artifacts/21st/C-CCUS/UCSP-1.png",
      description: "Researching regarding the Inequality in Mozambique in UCSP",
      date: "October 2025",
    },
    {
      title: "UCSP Research - Part 2",
      img: "/artifacts/21st/C-CCUS/UCSP-2.png",
      description: "Continuation of research on Inequality in Mozambique",
      date: "October 2025",
    },
  ],
  creativity: [
    {
      title: "SSAIGE Low-Fi Framework",
      img: "/artifacts/21st/CI/SSAIGE-1.png",
      description:
        "Low-fi framework design for SSAIGE - Study Simplifier, AI-based Gamified Education",
      date: "October 2025",
    },
    {
      title: "SSAIGE Website",
      img: "/artifacts/21st/CI/SSAIGE-2.png",
      description: "Actual implementation of SSAIGE website",
      date: "December 2025",
    },
    {
      title: "SSIMULATION UI Design",
      img: "/artifacts/21st/CI/SSIMULATION.png",
      description:
        "Framework/UI Design for SSIMULATION - Model of Statefields School Mabini Building",
      date: "September 2025",
    },
    {
      title: "Eternal Quest Game",
      img: "/artifacts/21st/CI/ETERNAL-QUEST.png",
      description:
        "Unity design and gameplay for Eternal Quest - Educational journey across academic strands",
      date: "September-October 2025",
    },
    {
      title: "ICAPS Conference Poster",
      img: "/artifacts/21st/CI/ICAPS.png",
      description:
        "Opening Poster for the 8th International Conference for Asian and Philippine Studies for G11 research",
      date: "May 2025",
    },
  ],
  collaboration: [
    {
      title: "Mathematics Competitions",
      img: "/artifacts/21st/CL/MATH-1.png",
      description:
        "Participated in various mathematics competitions, demonstrating problem-solving skills and mathematical reasoning under pressure",
      date: "Grade 11 - Grade 12",
    },
    {
      title: "Group Leader - General Mathematics",
      img: "/artifacts/21st/CL/MATH-1.png",
      description:
        "Served as group leader for Grade 11 General Mathematics, facilitating collaborative learning and guiding peers through complex mathematical concepts",
      date: "Grade 11 - Term 1",
    },
    {
      title: "Group Leader - Statistics",
      img: "/artifacts/21st/CL/MATH-2.png",
      description:
        "Led group discussions and activities in Statistics, helping classmates understand statistical analysis and data interpretation",
      date: "Grade 11 - Term 2",
    },
    {
      title: "Group Leader - Pre-Calculus",
      img: "/artifacts/21st/CL/MATH-3.png",
      description:
        "Guided peers through Pre-Calculus concepts, organizing study sessions and collaborative problem-solving activities",
      date: "Grade 12 - Term 1",
    },
    {
      title: "Group Leader - Basic Calculus",
      img: "/artifacts/21st/CL/MATH-4.png",
      description:
        "Facilitated group learning in Basic Calculus, breaking down complex calculus concepts for peer understanding",
      date: "Grade 12 - Term 2",
    },
    {
      title: "Data Analysis and Interpretation",
      img: "/artifacts/21st/CL/MATH-2.png",
      description:
        "Conducted comprehensive data analysis projects, applying statistical methods to real-world datasets and presenting findings",
      date: "Grade 11 - Grade 12",
    },
    {
      title: "Top Scorer - Mathematics Excellence",
      img: "/artifacts/21st/CL/MATH-3.png",
      description:
        "Consistently achieved exemplary scores across all mathematics subjects, demonstrating mastery in General Mathematics, Statistics, Pre-Calculus, and Basic Calculus",
      date: "Grade 11 - Grade 12",
    },
    {
      title: "Research Leadership - G11",
      img: "/artifacts/21st/CL/RESEARCH-1.png",
      description: "Leading research team in Grade 11 project",
      date: "Grade 11",
    },
    {
      title: "Research Leadership - G12",
      img: "/artifacts/21st/CL/RESEARCH-2.png",
      description: "Research leader for Grade 12 capstone project",
      date: "Grade 12",
    },
  ],
  "digital-literacy": [
    {
      title: "AI Code Understanding",
      img: "/artifacts/21st/CIMTL/COMPUTING.png",
      description: "Understanding and analyzing code generated by AI tools",
      date: "Entire Semester",
    },
    {
      title: "Research Literature Review",
      img: "/artifacts/21st/CIMTL/INFO.png",
      description:
        "Using consensus.ai for RRL and verification for research alignment",
      date: "Semester 1-2, Grade 12",
    },
    {
      title: "Mini-Cher Media Application",
      img: "/artifacts/21st/CIMTL/MEDIA.png",
      description:
        "Teaching dimensions of people media through mini-cher application",
      date: "October 2, 2025",
    },
    {
      title: "AI Framework Development",
      img: "/artifacts/21st/CIMTL/TECH.png",
      description:
        "Creating an AI framework for SSI Institutional Development Office (c/o Miss Sherilyn Ambion)",
      date: "January 10, 2026",
    },
  ],
  communication: [
    {
      title: "Mini-Cher Chemistry Teaching",
      img: "/artifacts/21st/Comm/mini-cher-1.png",
      description: "Teaching General Chemistry to Grade 11 students",
      date: "September 26, 2024",
    },
    {
      title: "Mini-Cher MIL Photography",
      img: "/artifacts/21st/Comm/mini-cher-2.png",
      description:
        "Teaching Media and Information Literacy photography techniques for Sir Chester",
      date: "September 24, 2025",
    },
    {
      title: "Research Presentation",
      img: "/artifacts/21st/Comm/research.png",
      description: "Presenting Grade 12 research at title defense",
      date: "September 1, 2025",
    },
    {
      title: "Dasma Research Congress",
      img: "/artifacts/21st/Comm/drc.png",
      description: "Presenting at the 2nd KLD Dasma Research Congress",
      date: "2025",
    },
  ],
  "control-coping": [
    {
      title: "Biology Catch-Up Schedule",
      img: "/artifacts/21st/CCS/Schedule.png",
      description:
        "Digital schedule organization for Biology review catch-up day",
      date: "November 2025",
    },
    {
      title: "Research Schedule Management",
      img: "/artifacts/21st/CCS/sched-RE.png",
      description: "Creating and managing schedule for research project",
      date: "February 3, 2026",
    },
  ],
  "social-responsibility": [
    {
      title: "SDG 12 - Responsible AI Use",
      img: "/artifacts/21st/SRGEA/EMPOW.png",
      description:
        "Performance task on SDG 12 focusing on responsible use of AI",
      date: "2025",
    },
    {
      title: "Earth Science Mindmap - Semester 1",
      img: "/artifacts/21st/SRGEA/EARTH-SCI-1.png",
      description: "MI Mindmap/Notebook for Earth Science Semester 1",
      date: "Semester 1",
    },
    {
      title: "Earth Science Mindmap - Semester 2",
      img: "/artifacts/21st/SRGEA/EARTH-SCI-2.png",
      description: "MI Mindmap/Notebook for Earth Science Semester 2",
      date: "Semester 2",
    },
  ],
  "lifelong-learning": [
    {
      title: "General Biology Digital Notebook",
      img: "/artifacts/21st/LLSDPM/notebook.png",
      description: "Comprehensive digital notebook for General Biology 1",
      date: "1st Semester - Grade 12",
    },
    {
      title: "Chemistry Lesson Plan",
      img: "/artifacts/21st/LLSDPM/lesson-plan-chem.png",
      description:
        "Detailed lesson plan created for mini-cher chemistry teaching session",
      date: "September 26, 2024",
    },
  ],
  "critical-thinking": [
    {
      title: "Scaled Down Distances Problem",
      img: "/artifacts/21st/CT-PS/Astro-1.png",
      description:
        "Figure answer demonstrating problem-solving approach for scaled down distances in IAAC (International Astronomy and Astrophysics Competition)",
      date: "November 2025",
    },
    {
      title: "Molarity Calculation Using I-P-O Method",
      img: "/artifacts/21st/CT-PS/Chem-1.png",
      description:
        "Applied Input-Process-Output method to solve molarity problems in chemistry",
      date: "January 2025",
    },
    {
      title: "PV=NRT Law Diagram",
      img: "/artifacts/21st/CT-PS/Chem-p6-1.png",
      description:
        "Visual diagram explaining the ideal gas law (PV=NRT) for International Physics Competition",
      date: "January 2026",
    },
    {
      title: "Static Balance Problem",
      img: "/artifacts/21st/CT-PS/P6-1.png",
      description:
        "Diagram showing systematic approach to solving static balance problems in International Physics Competition",
      date: "January 2026",
    },
  ],
};

const SKILLS_DATA = [
  {
    id: "collaboration",
    title: "Collaboration and Leadership",
    icon: <Users className="w-6 h-6" />,
    color: "border-blue-500",
    description:
      "The ability to work effectively with diverse teams and take initiative to lead projects toward a shared goal.",
    suggestedArtifact:
      "Team Project Management Board (Trello/GitHub) showing task delegation and collaborative problem-solving logs.",
    artifactCount: ARTIFACTS_DATA["collaboration"]?.length || 0,
  },
  {
    id: "critical-thinking",
    title: "Critical Thinking and Problem Solving",
    icon: <Brain className="w-6 h-6" />,
    color: "border-orange-500",
    description:
      "Analyzing information and using logical reasoning to solve complex, ill-structured problems.",
    suggestedArtifact:
      "Step-by-step Process Flowchart for a chemical titration or a Root Cause Analysis report for a technical failure.",
    artifactCount: ARTIFACTS_DATA["critical-thinking"]?.length || 0,
  },
  {
    id: "creativity",
    title: "Creativity and Innovation",
    icon: <Lightbulb className="w-6 h-6" />,
    color: "border-yellow-400",
    description:
      "Developing novel solutions and original ideas using creative thinking techniques and design thinking.",
    suggestedArtifact:
      "UI/UX Blueprint for an AI-powered Lesson Summarizer or a functional prototype of an original game.",
    artifactCount: ARTIFACTS_DATA["creativity"]?.length || 0,
  },
  {
    id: "social-responsibility",
    title: "Social Responsibility, Cultural, Global & Environmental Awareness",
    icon: <Globe className="w-6 h-6" />,
    color: "border-green-500",
    description:
      "Understanding global issues and acting with ethical responsibility towards society and the environment.",
    suggestedArtifact:
      "A Case Study on UN Sustainable Development Goals or a community service project report.",
    artifactCount: ARTIFACTS_DATA["social-responsibility"]?.length || 0,
  },
  {
    id: "communication",
    title: "Communication and Conveying",
    icon: <MessageSquare className="w-6 h-6" />,
    color: "border-emerald-400",
    description:
      "Expressing ideas clearly through various media and effectively conveying information to diverse audiences.",
    suggestedArtifact:
      "A recorded technical presentation (TED Talk style) or an Infographic summarizing complex data. Research proposal with clear communication of objectives, methods, and expected outcomes.",
    artifactCount: ARTIFACTS_DATA["communication"]?.length || 0,
  },
  {
    id: "digital-literacy",
    title: "Computing and Information, Media, and Technology Literacies",
    icon: <Cpu className="w-6 h-6" />,
    color: "border-cyan-400",
    description:
      "Mastery over digital tools and the ability to consume/create media critically and safely.",
    suggestedArtifact:
      "A Documentation of 'Responsible AI Use' showing prompt engineering logs and ethical source citations. Mini-cher on MIL photography",
    artifactCount: ARTIFACTS_DATA["digital-literacy"]?.length || 0,
  },
  {
    id: "lifelong-learning",
    title: "Lifelong Learning, Self-Direction and Personal Management",
    icon: <Compass className="w-6 h-6" />,
    color: "border-purple-500",
    description:
      "Taking ownership of learning, setting goals, and managing time and resources independently.",
    suggestedArtifact:
      "A Metacognitive Reflection Journal or a personalized 'Learning Goal Action Plan' for a new skill.",
    artifactCount: ARTIFACTS_DATA["lifelong-learning"]?.length || 0,
  },
  {
    id: "citizenship",
    title: "Citizenship and Cross-Cultural Understanding Skills",
    icon: <Flag className="w-6 h-6" />,
    color: "border-red-400",
    description:
      "Engaging as an active citizen and respecting cultural diversity in local and global contexts.",
    suggestedArtifact:
      "A Cultural Comparison Essay or a certificate/reflection from a cross-cultural exchange program.",
    artifactCount: ARTIFACTS_DATA["citizenship"]?.length || 0,
  },
  {
    id: "control-coping",
    title: "Control and Coping Skills",
    icon: <Activity className="w-6 h-6" />,
    color: "border-pink-500",
    description:
      "Resilience, stress management, and maintaining emotional stability during challenging academic or professional tasks.",
    suggestedArtifact:
      "A Stress Management Portfolio or a reflective essay on overcoming a significant project failure.",
    artifactCount: ARTIFACTS_DATA["control-coping"]?.length || 0,
  },
];

export default function TwentyFirstCenturySkills() {
  const [activeSkill, setActiveSkill] = useState<
    (typeof SKILLS_DATA)[0] | null
  >(null);
  const [isDark, setIsDark] = useState(true);

  return (
    <div
      className={`min-h-screen font-sans transition-colors duration-300 ${isDark ? "bg-gray-950 text-gray-100" : "bg-gray-50 text-gray-900"} selection:bg-blue-500 selection:text-white`}
    >
      <Navbar isDark={isDark} onToggleTheme={() => setIsDark(!isDark)} />

      <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
        {activeSkill ? (
          // Skill Detail View
          <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
            <button
              onClick={() => setActiveSkill(null)}
              className="flex items-center gap-2 text-blue-400 hover:text-blue-300 mb-8 font-medium transition-colors"
            >
              <ArrowLeft size={20} /> Back to Dashboard
            </button>

            {/* I. Introduction */}
            <div className="mb-8 sm:mb-12">
              <h2 className="text-2xl sm:text-3xl lg:text-4xl font-bold mb-6 sm:mb-8 flex items-center gap-2 sm:gap-3">
                <span className="text-blue-400">I.</span> Introduction
              </h2>
              <div
                className={`p-4 sm:p-6 lg:p-8 rounded-2xl border-l-4 ${activeSkill.color} ${isDark ? "bg-gray-900" : "bg-white shadow-lg"}`}
              >
                <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3 sm:gap-4 mb-4">
                  <div
                    className={`p-2 sm:p-3 rounded-xl text-blue-400 ${isDark ? "bg-gray-800" : "bg-gray-100"}`}
                  >
                    {activeSkill.icon}
                  </div>
                  <h3 className="text-xl sm:text-2xl lg:text-3xl font-bold">
                    {activeSkill.title}
                  </h3>
                </div>
                <p
                  className={`text-base sm:text-lg lg:text-xl max-w-3xl mb-4 sm:mb-6 leading-relaxed ${isDark ? "text-gray-400" : "text-gray-600"}`}
                >
                  {activeSkill.description}
                </p>
                {/* <div className="bg-blue-500/10 border border-blue-500/20 p-3 sm:p-4 rounded-lg inline-block">
                  <span className="text-blue-400 font-bold text-sm uppercase mr-2">
                    Suggested Artifact:
                  </span>
                  <span className={isDark ? "text-gray-300" : "text-gray-700"}>
                    {activeSkill.suggestedArtifact}
                  </span>
                </div> */}
              </div>
            </div>

            {/* II. Artifacts */}
            <div className="mb-8 sm:mb-12">
              <h2 className="text-2xl sm:text-3xl lg:text-4xl font-bold mb-6 sm:mb-8 flex items-center gap-2 sm:gap-3">
                <span className="text-blue-400">II.</span> Artifacts
              </h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6">
                {ARTIFACTS_DATA[activeSkill.id]?.map((artifact, index) => (
                  <div
                    key={index}
                    className={`rounded-xl overflow-hidden border transition-all group ${isDark ? "bg-gray-800 border-gray-700 hover:border-blue-500" : "bg-white border-gray-300 hover:border-blue-500 shadow-md"}`}
                  >
                    <div
                      className={`h-48 flex items-center justify-center relative ${isDark ? "bg-gray-900" : "bg-gray-100"}`}
                    >
                      {artifact.img ? (
                        <img
                          src={artifact.img}
                          alt={artifact.title}
                          className="w-full h-full object-cover"
                        />
                      ) : (
                        <div
                          className={`flex flex-col items-center ${isDark ? "text-gray-600" : "text-gray-400"}`}
                        >
                          <span className="text-xs font-mono">NO_IMAGE</span>
                        </div>
                      )}
                    </div>
                    <div className="p-4">
                      <h4
                        className={`text-sm font-bold mb-2 uppercase tracking-wider ${isDark ? "text-gray-300" : "text-gray-700"}`}
                      >
                        {artifact.title}
                      </h4>
                      <p
                        className={`text-sm leading-relaxed mb-2 ${isDark ? "text-gray-400" : "text-gray-600"}`}
                      >
                        {artifact.description}
                      </p>
                      <p
                        className={`text-xs font-medium ${isDark ? "text-blue-400" : "text-blue-500"}`}
                      >
                        {artifact.date}
                      </p>
                    </div>
                  </div>
                ))}

                {(!ARTIFACTS_DATA[activeSkill.id] ||
                  ARTIFACTS_DATA[activeSkill.id].length === 0) && (
                  <div className="col-span-full text-center py-12">
                    <p className={isDark ? "text-gray-500" : "text-gray-400"}>
                      No artifacts available yet for this skill. Check back
                      soon!
                    </p>
                  </div>
                )}
              </div>
            </div>
          </div>
        ) : (
          // Dashboard View
          <div className="animate-in fade-in duration-700">
            {/* Header Section */}
            <header className="mb-16">
              <div className="inline-block px-3 py-1 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 text-xs font-bold uppercase tracking-widest mb-4">
                Professional Portfolio
              </div>
              <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl xl:text-7xl font-extrabold mb-4 sm:mb-6 leading-tight">
                My Personal{" "}
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-emerald-400">
                  21st Century
                </span>{" "}
                Skills Portfolio
              </h1>

              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 sm:gap-8 items-start mb-12 sm:mb-16">
                <div className="lg:col-span-2">
                  <div
                    className={`p-4 sm:p-6 rounded-2xl border backdrop-blur-sm ${isDark ? "bg-gray-900/50 border-gray-800" : "bg-white/50 border-gray-200 shadow-lg"}`}
                  >
                    <p
                      className={`text-base sm:text-lg leading-relaxed italic ${isDark ? "text-gray-400" : "text-gray-600"}`}
                    >
                      This portfolio represents my journey of growth and
                      development throughout senior high school. It shows where
                      I have been, what I have learned, and importantly, what I
                      still need to improve. I now understand that being a
                      21st-century learner means continuously developing these
                      skills throughout my life, and I am prepared to continue
                      this journey of learning. (scroll down to see the skills
                      and reflection)
                    </p>
                  </div>
                </div>

                {/* Profile Card snippet */}
                <div
                  className={`p-6 rounded-2xl border shadow-2xl ${isDark ? "bg-gradient-to-br from-gray-800 to-gray-900 border-gray-700" : "bg-gradient-to-br from-gray-100 to-gray-200 border-gray-300"}`}
                >
                  <div
                    className={`w-24 h-24 rounded-full mx-auto mb-4 border-4 shadow-xl overflow-hidden ${isDark ? "border-gray-900" : "border-white"}`}
                  >
                    <Image
                      src="/grad.jpg"
                      alt="Gene Lorenz"
                      width={96}
                      height={96}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div className="text-center">
                    <h2 className="text-xl font-bold">Gene Lorenz</h2>
                    <p className="text-blue-400 text-sm font-medium mb-4">
                      Nominated 21st Century Learner
                    </p>
                    <div className="space-y-2">
                      <div
                        className={`py-2 rounded text-xs font-mono text-emerald-400 border border-emerald-500/20 ${isDark ? "bg-gray-950/50" : "bg-emerald-50"}`}
                      >
                        ✓ 9 Skills Documented
                      </div>
                      <div
                        className={`py-2 rounded text-xs font-mono text-blue-400 border border-blue-500/20 ${isDark ? "bg-gray-950/50" : "bg-blue-50"}`}
                      >
                        ✓{" "}
                        {Object.values(ARTIFACTS_DATA).reduce(
                          (sum, artifacts) => sum + artifacts.length,
                          0,
                        )}{" "}
                        Artifacts Linked
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </header>

            {/* Skills Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6">
              {SKILLS_DATA.map((skill) => (
                <div
                  key={skill.id}
                  onClick={() => setActiveSkill(skill)}
                  className={`group relative p-4 sm:p-6 rounded-xl sm:rounded-2xl border-x border-b transition-all cursor-pointer overflow-hidden border-t-4 ${skill.color} ${isDark ? "bg-gray-900/30 border-x-gray-800 border-b-gray-800 hover:bg-gray-900" : "bg-white border-x-gray-200 border-b-gray-200 hover:shadow-xl"}`}
                >
                  <div className="flex justify-between items-start mb-4">
                    <div
                      className={`p-2 rounded-lg group-hover:scale-110 transition-transform ${isDark ? "bg-gray-800" : "bg-gray-100"}`}
                    >
                      {skill.icon}
                    </div>
                    <ChevronRight className="text-gray-600 group-hover:text-blue-400 group-hover:translate-x-1 transition-all" />
                  </div>
                  <h3 className="text-lg font-bold mb-2 group-hover:text-blue-400 transition-colors">
                    {skill.title}
                  </h3>
                  <p
                    className={`text-sm line-clamp-2 ${isDark ? "text-gray-500" : "text-gray-600"}`}
                  >
                    {skill.description}
                  </p>
                  <div
                    className={`mt-4 pt-4 border-t flex items-center justify-between ${isDark ? "border-gray-800/50" : "border-gray-200"}`}
                  >
                    <span
                      className={`text-[10px] font-bold uppercase tracking-tighter ${isDark ? "text-gray-600" : "text-gray-500"}`}
                    >
                      {skill.artifactCount} Artifacts
                    </span>
                    <div className="flex items-center gap-1">
                      <span className="text-xs font-bold text-blue-400">
                        {skill.artifactCount}
                      </span>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* Overall Reflection Section */}
            <div className="mt-12 sm:mt-16">
              <div
                className={`p-4 sm:p-6 lg:p-8 rounded-2xl border ${isDark ? "bg-gray-900 border-gray-800" : "bg-white border-gray-200 shadow-lg"}`}
              >
                <h2 className="text-2xl sm:text-3xl font-bold mb-4 sm:mb-6 flex items-center gap-2 sm:gap-3">
                  <Compass className="text-blue-400" size={24} />
                  Overall Reflection
                </h2>
                <div className="space-y-3 sm:space-y-4">
                  <p
                    className={`text-sm sm:text-base leading-relaxed ${isDark ? "text-gray-300" : "text-gray-700"}`}
                  >
                    Looking back at my journey through senior high school, I've
                    come to understand that being a 21st-century learner is more
                    complex than I initially thought. These nine skills are not
                    separate categories that I can simply check off a list.
                    Instead, they connect with each other and overlap in
                    unexpected ways, pushing me to grow in directions I had not
                    planned for.
                  </p>
                  <p
                    className={`leading-relaxed ${isDark ? "text-gray-300" : "text-gray-700"}`}
                  >
                    As I review these artifacts, I notice patterns that were not
                    clear to me while working on them. My creativity projects
                    like SSAIGE, SSIMULATION, and Eternal Quest all needed
                    collaboration skills that I had to develop along the way.
                    Similarly, when I taught chemistry and photography during
                    mini-cher sessions, I discovered that my digital literacy
                    skills needed improvement. These experiences taught me that
                    different skills support and strengthen each other.
                  </p>
                  <p
                    className={`leading-relaxed ${isDark ? "text-gray-300" : "text-gray-700"}`}
                  >
                    The research work from Grade 11 to Grade 12 has been
                    particularly meaningful for my development. Beyond the
                    academic knowledge I gained about topics like inequality in
                    Mozambique and Filipino cultural practices, I learned
                    important lessons about leadership. Leading a research team
                    taught me that effective leadership is not about being the
                    most knowledgeable person, but about knowing when to ask for
                    help and creating space for others to contribute. The
                    presentations at the Dasma Research Congress and ICAPS were
                    successful, but the moments when I struggled to answer
                    questions or had to admit I needed to research further
                    taught me even more about growth and learning.
                  </p>
                  <p
                    className={`leading-relaxed ${isDark ? "text-gray-300" : "text-gray-700"}`}
                  >
                    I have noticed a significant change in how I approach
                    problems now compared to before. In the past, I would either
                    feel overwhelmed or rush to find the first solution that
                    came to mind. Now, I take time to think carefully, consider
                    different perspectives, and question my initial assumptions.
                    For example, when building the AI framework for the
                    Institutional Development Office of SSI, I spent
                    considerable time thinking about ethical concerns and
                    sustainability. My participation in international
                    competitions like IAAC and the International Physics
                    Competition further strengthened my analytical skills,
                    teaching me to break down complex problems systematically.
                    This reflects how my critical thinking skills have developed
                    over time.
                  </p>
                  <p
                    className={`leading-relaxed ${isDark ? "text-gray-300" : "text-gray-700"}`}
                  >
                    My time management skills have also improved, though I still
                    face challenges. The schedules I created for Biology
                    catch-up and research planning show that I have moved from
                    reacting to problems at the last minute to planning ahead
                    more carefully. While I still struggle sometimes, I can see
                    clear progress. The same applies to managing stress. I have
                    learned better strategies for coping with academic pressure
                    compared to my earlier high school years.
                  </p>
                  <p
                    className={`leading-relaxed ${isDark ? "text-gray-300" : "text-gray-700"}`}
                  >
                    The most important growth I have experienced is not visible
                    in any single project or artifact. It is in the way I think
                    now. I have learned to see connections between different
                    areas—social issues, environmental concerns, and ethical
                    questions. The SDG work and Earth Science studies changed
                    how I understand the world and how everything is connected.
                    My math collaborations showed me that people think
                    differently, and this diversity is actually valuable. The
                    citizenship research on different cultures challenged my
                    assumptions and expanded my understanding of the world
                    beyond my immediate experience.
                  </p>
                  <p
                    className={`leading-relaxed ${isDark ? "text-gray-300" : "text-gray-700"}`}
                  >
                    As I move forward beyond senior high school, I carry these
                    experiences and lessons with me. This portfolio is not just
                    a collection of completed work, but a foundation for
                    continuous growth. The skills I have developed here will
                    continue to evolve as I face new challenges and
                    opportunities. I am grateful for the learning experiences
                    that have shaped me, and I look forward to applying these
                    competencies in my future academic and professional
                    endeavors. Being a 21st-century learner is not a destination
                    but an ongoing commitment to growth, adaptation, and
                    meaningful contribution to society.
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer
        className={`mt-20 border-t py-12 ${isDark ? "border-gray-900 bg-gray-950" : "border-gray-200 bg-white"}`}
      >
        <div className="max-w-6xl mx-auto px-6 text-center">
          <p
            className={`text-sm mb-4 ${isDark ? "text-gray-600" : "text-gray-500"}`}
          >
            Built with Next.js, Tailwind CSS, and Passion for Innovation.
          </p>
          <div className="flex justify-center gap-6 grayscale opacity-50">
            <div className="w-8 h-8 bg-white rounded-full"></div>
            <div className="w-8 h-8 bg-blue-500 rounded-full"></div>
            <div className="w-8 h-8 bg-emerald-500 rounded-full"></div>
          </div>
        </div>
      </footer>
    </div>
  );
}
